set(CMAKE_SYSTEM_NAME QNX)

set(CMAKE_SYSTEM_VERSION 7)

set(CMAKE_C_COMPILER   $ENV{TOOLCHAIN_ROOT}/qcc)
set(CMAKE_CXX_COMPILER $ENV{TOOLCHAIN_ROOT}/qcc)

set(CMAKE_FIND_ROOT_PATH $ENV{QNX_TARGET})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
